AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Fraud Detection System - Capstone Starter

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        ACCOUNTS_TABLE: !Ref AccountsTable
        TRANSACTIONS_TABLE: !Ref TransactionsTable

Resources:
  AccountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: account_id
          AttributeType: S
      KeySchema:
        - AttributeName: account_id
          KeyType: HASH
      TableName: Accounts

  TransactionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: transaction_id
          AttributeType: S
      KeySchema:
        - AttributeName: transaction_id
          KeyType: HASH
      TableName: Transactions

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ..
      Handler: src.api.app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AccountsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TransactionsTable

  ProcessTransactionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ..
      Handler: src.lambdas.process_transaction.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AccountsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TransactionsTable

  TwilioWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ..
      Handler: src.lambdas.twilio_webhook.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TransactionsTable

Outputs:
  AccountsTableName:
    Value: !Ref AccountsTable
  TransactionsTableName:
    Value: !Ref TransactionsTable
